import { ContextMap, EntityStore } from './contextTypes';

const BACKTRACK_START = '<!-- backtrack:start -->';
const BACKTRACK_END = '<!-- backtrack:end -->';

export function generateClaudeMd(ctx: ContextMap, store: EntityStore): string {
  const updated = ctx.lastUpdated.slice(0, 10);
  const openBugs = store.bugs.filter(b => b.status === 'open');
  const openTodos = store.todos.filter(t => t.status === 'open');

  const lines: string[] = [
    `# Project Context — ${ctx.project}`,
    '',
    BACKTRACK_START,
    `<!-- Auto-generated by Backtrack on ${updated}. Do not edit between these tags. -->`,
    `<!-- Full knowledge map: .backtrack/context.json -->`,
    '',
    '## Quick Summary',
  ];

  if (ctx.quickContext.currentFocus) {
    lines.push(`**Current focus:** ${ctx.quickContext.currentFocus}`);
  }

  lines.push(`**Sessions analyzed:** ${ctx.sessionsAnalyzed}  `);
  lines.push(`**Last updated:** ${updated}`);
  lines.push('');

  // Stack
  const stackParts: string[] = [];
  if (ctx.stack.languages.length) stackParts.push(ctx.stack.languages.join(', '));
  if (ctx.stack.frontend.length) stackParts.push(ctx.stack.frontend.join(', '));
  if (ctx.stack.backend.length) stackParts.push(ctx.stack.backend.join(', '));
  if (ctx.stack.databases.length) stackParts.push(ctx.stack.databases.join(', '));
  if (stackParts.length) {
    lines.push(`**Stack:** ${stackParts.join(' · ')}`);
    lines.push('');
  }

  // Recent decisions
  if (ctx.quickContext.recentDecisions.length) {
    lines.push('## Key Decisions');
    for (const d of store.decisions.slice(-5)) {
      lines.push(`- **${d.title}**`);
      if (d.reason) lines.push(`  Reason: ${d.reason}`);
    }
    lines.push('');
  }

  // Open issues
  if (openBugs.length) {
    lines.push('## Open Issues');
    for (const b of openBugs.slice(0, 5)) {
      lines.push(`- [BUG] ${b.title}`);
      if (b.workaround) lines.push(`  Workaround: ${b.workaround}`);
    }
    lines.push('');
  }

  // Conventions
  if (store.conventions.length) {
    lines.push('## Conventions');
    for (const c of store.conventions.slice(0, 8)) {
      lines.push(`- ${c.rule}`);
    }
    lines.push('');
  }

  // Open TODOs
  if (openTodos.length) {
    lines.push('## Current State / TODOs');
    const high = openTodos.filter(t => t.priority === 'high');
    const rest = openTodos.filter(t => t.priority !== 'high');
    for (const t of [...high, ...rest].slice(0, 8)) {
      const marker = t.priority === 'high' ? '**[HIGH]**' : '';
      lines.push(`- ${marker} ${t.title}`);
    }
    lines.push('');
  }

  // Last session
  if (ctx.quickContext.lastSession) {
    const ls = ctx.quickContext.lastSession;
    lines.push('## Last Session');
    lines.push(`- ID: \`${ls.id.slice(0, 8)}\``);
    lines.push(`- Date: ${ls.date}`);
    lines.push(`- Summary: ${ls.summary}`);
    lines.push('');
  }

  // Timeline (last 5 events)
  if (store.timeline.length) {
    lines.push('## Recent Timeline');
    for (const e of store.timeline.slice(-5)) {
      lines.push(`- ${e.date} — ${e.title}`);
    }
    lines.push('');
  }

  lines.push(BACKTRACK_END);
  lines.push('');

  return lines.join('\n');
}

/**
 * Update an existing CLAUDE.md file by replacing the backtrack section.
 * Leaves any content outside the backtrack tags untouched.
 */
export function updateExistingClaudeMd(
  existing: string,
  ctx: ContextMap,
  store: EntityStore
): string {
  const newSection = generateClaudeMd(ctx, store);

  const startIdx = existing.indexOf(BACKTRACK_START);
  const endIdx = existing.indexOf(BACKTRACK_END);

  if (startIdx === -1 || endIdx === -1) {
    // No existing section — append
    return existing.trimEnd() + '\n\n' + newSection;
  }

  const before = existing.slice(0, startIdx);
  const after = existing.slice(endIdx + BACKTRACK_END.length);
  return before + newSection + after.trimStart();
}
